language: java

jdk:
  - openjdk8

os:
  - linux
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
  - ./gradlew build --refresh-dependencies --no-daemon --continue
after_success:
  - bash <(curl -s https://codecov.io/bash)